Added better tests

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -1,6 +1,6 @@
 # Created by: WestleyR
 # email: westleyr@nym.hush.com
-# Date: Aug 10, 2019
+# Date: Aug 18, 2019
 # https://github.com/WestleyR/list-files
 # Version-1.0.0
 #
@@ -12,8 +12,6 @@
 # This software is licensed under a Clear BSD License.
 #
 
-set -e
-
 if [ ! $(command -v "lf") ]; then
 	echo "ERROR: 'lf' not found in PATH, you should install lf"
 	exit 1
@@ -22,18 +20,26 @@ fi
 echo "Running all tests..."
 echo
 
-test_files=`ls tests/`
+all_tests_num=0
+tests_failed_num=0
+tests_failed=""
+
+test_files=`ls -1 tests/ | sort -n`
 
 for t in $test_files; do
 	if [ -f "tests/${t}" ]; then
-		echo "Running test: ${t} ... "
-		bash "tests/${t}"
-#		echo
+		echo "Testing: ${t}:"
+		if ! bash "tests/${t}"; then
+			echo "test failed: ${t}"
+			((tests_failed_num+=1))
+			tests_failed=`echo "${test_failed} ${t}"`
+		fi
+		((all_tests_num+=1))
 	fi
 done
 
 echo
-echo "All tests passed!"
+echo "All tests ran with ${tests_failed_num} test(s) failed, of ${all_tests_num}"
 
 #
 # End run-tests
diff --git a/tests-funcs b/tests-funcs
--- a/tests-funcs
+++ b/tests-funcs
@@ -13,32 +13,50 @@
 #
 
 # usage:
-# run-test <test-name> <test-command> <expect-to-contain-output> <expect-exit-code>
+# run-test <test-name> <test-command> <expect-to-contain-output> <also-expect-to-contain> <expect-exit-code>
 #
 run-test() {
 	test_name=$1
 	test_cmd=$2
 	expect_contain_out=$3
-	expect_exit_code=$4
+	also_expect_contain_out=$4
+	expect_exit_code=$5
 
+	green='\033[0;32m'
+	red='\033[0;31m'
+	creset='\033[0m'
 
-	echo "Running: ${test_name} ..."
+	echo -n "Running: ${test_name} ... "
 
-	output=`$test_cmd 2>&1`
+	output=`/bin/sh -c "$test_cmd" 2>&1`
 	exit_code=$?
 	if [ $exit_code -ne $expect_exit_code ]; then
-		echo "FAIL: expecting exit code: ${expect_exit_code}, got ${exit_code}"
+		echo -e "${red}FAIL${creset} "
+		echo "expecting exit code: ${expect_exit_code}, got ${exit_code}"
 		echo "while running: ${test_cmd}"
+		echo "out: ${output}"
 		exit 1
 	fi
 
-	if [[ -n $2 ]]; then
-		if [[ ! -n $(echo "$output" | grep "$expect_contain_out") ]]; then
-			echo "FAIL: expected outout to contain: ${expect_contain_out}, got: ${output}"
+	line_output=`echo "$output" | grep "$expect_contain_out"`
+	if [[ -n $expect_contain_out ]]; then
+		if [[ ! -n $line_output ]]; then
+			echo -e "${red}FAIL${creset} "
+			echo "expected outout to contain: ${expect_contain_out}, got: ${output}"
 			echo "while running: ${test_cmd}"
 			exit 1
 		fi
 	fi
+	if [[ -n $also_expect_contain_out ]]; then
+		if [[ ! -n $(echo "$line_output" | grep "$also_expect_contain_out") ]]; then
+			echo -e "${red}FAIL${creset} "
+			echo "expected outout to contain: ${also_expect_contain_out}, got: ${line_output}"
+			echo "while running: ${test_cmd}"
+			exit 1
+		fi
+	fi
+
+	echo -e "${green}PASS${creset}"
 }
 
 #
