Working tests v2

diff --git a/tests-funcs b/tests-funcs
--- a/tests-funcs
+++ b/tests-funcs
@@ -1,8 +1,8 @@
 # Created by: WestleyR
 # email: westleyr@nym.hush.com
-# Date: Aug 10, 2019
-# https://github.com/WestleyR/clint
-# version-1.0.3
+# Date: Aug 18, 2019
+# https://github.com/WestleyR/list-files
+# version-1.0.0
 #
 # The Clear BSD License
 #
@@ -13,33 +13,33 @@
 #
 
 # usage:
-# run-tests <command> <contains_out> <exit_code>
-
+# run-test <test-name> <test-command> <expect-to-contain-output> <expect-exit-code>
+#
 run-test() {
-	echo "Running: $1 ..."
+	test_name=$1
+	test_cmd=$2
+	expect_contain_out=$3
+	expect_exit_code=$4
 
-	output=`$1`
-	if [ $? != $3 ]; then
-		echo "FAIL: expecting exit code ${3}, got $?"
-		echo "while running: ${1}"
+
+	echo "Running: ${test_name} ..."
+
+	output=`$test_cmd 2>&1`
+	exit_code=$?
+	if [ $exit_code -ne $expect_exit_code ]; then
+		echo "FAIL: expecting exit code: ${expect_exit_code}, got ${exit_code}"
+		echo "while running: ${test_cmd}"
 		exit 1
 	fi
 
-#	echo "STDOUT: $output"
-
-	if [ ! -n $2 ]; then
-		if [[ ! -n $(echo "$output" | grep "$2") ]]; then
-			echo "FAIL: expected outout to contain: $2, got: $output"
-			echo "while running: $1"
+	if [[ -n $2 ]]; then
+		if [[ ! -n $(echo "$output" | grep "$expect_contain_out") ]]; then
+			echo "FAIL: expected outout to contain: ${expect_contain_out}, got: ${output}"
+			echo "while running: ${test_cmd}"
 			exit 1
 		fi
 	fi
-
-
 }
-
-
-
 
 #
 # End tests-funcs
